# Generated by Django 3.1 on 2020-08-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.FileField(upload_to='Model')),
                ('intents', models.FileField(upload_to='Model')),
                ('words', models.FileField(upload_to='Model')),
                ('chatbot_model', models.FileField(upload_to='Model')),
            ],
        ),
    ]
